### ISSUE TITLE
Get.full.posterior bug

### ISSUE THREAD

**Issue by stephens999** [stephenslab/mr.ash.alpha#3]
I think the posterior variance s2 should be scaled by the residual variance

**Comment by pcarbo** [comment]
Making these changes,

```r
s2 = fit$sigma2 / outer(fit$data$w, 1/fit$data$sa2, '+');
m = bw * s2 / fit$sigma2;
```

the means and variances look correct, but not the phi's. I'm having trouble following how the phi's are being calculated.

**Comment by stephens999** [comment]
ugg! I don't know why that was never fixed.
I have pushed a fix.

**Comment by pcarbo** [comment]
@stephens999 I think we can close this issue?
